# FLASK PARAMETERS
port: 5005
bind_hosts: 0.0.0.0

# APPLICATION PARAMETERS
cachetime: 60 # seconds
mapchangetime_s: 45
log_visits: 1 # 0, 1
visits_logfile: visits.log # might require absolute path
enable_stats_page: True # Turning this on provides a DDOS attack vector

# KR META INFO
phase1timelimit: 10
phase2start: 15.08.2021 18:00
phase2timelimit: 20
compend: 31.08.2021 18:00
min_mapid: 76
max_mapid: 150

# LOGGING
logtype: STDOUT # STDOUT, FILE
logfile: flask.log # might require absolute path
loglevel: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL
